"""initial_schema

Revision ID: 81ba6d068211
Revises: 
Create Date: 2026-04-23 13:36:32.077185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ba6d068211'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aianalyses_ticker_created', 'ai_analyses', ['ticker', 'created_at'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dividend_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('annual_dps', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'year', name='uq_divhistory_ticker_year')
    )
    op.create_index('idx_divhistory_ticker_year', 'dividend_history', ['ticker', 'year'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('dividends_added', sa.Integer(), nullable=False),
    sa.Column('transactions_added', sa.Integer(), nullable=False),
    sa.Column('positions_updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('instrument_name', sa.String(length=200), nullable=False),
    sa.Column('instrument_type', sa.String(length=10), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('open_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('etoro_position_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('change_pct_day', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_pricehistory_ticker_date')
    )
    op.create_index('idx_pricehistory_ticker_date', 'price_history', ['ticker', 'date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etoro_id', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etoro_id')
    )
    op.create_index('idx_transactions_ticker_date', 'transactions', ['ticker', 'transaction_date'], unique=False)
    op.create_table('dividend_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('units_at_payment', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_divpayments_ticker_date', 'dividend_payments', ['ticker', 'payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_divpayments_ticker_date', table_name='dividend_payments')
    op.drop_table('dividend_payments')
    op.drop_index('idx_transactions_ticker_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_pricehistory_ticker_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('price_cache')
    op.drop_table('positions')
    op.drop_table('import_runs')
    op.drop_index('idx_divhistory_ticker_year', table_name='dividend_history')
    op.drop_table('dividend_history')
    op.drop_table('app_settings')
    op.drop_index('idx_aianalyses_ticker_created', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
